# Generated by Django 4.1.2 on 2022-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_produc', models.CharField(max_length=60)),
                ('precio_produc', models.PositiveIntegerField(default=0)),
                ('descripcion_produc', models.CharField(max_length=60)),
                ('imagen_produc', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
